### ISSUE TITLE
Tease bicoloring at the end of the coloring section

### ISSUE THREAD

**Issue by gdalle** [adrhill/iclr2025-sparse-autodiff#38]
Simple visualization in the same style

$$ \begin{pmatrix}
1 & 1 & 1 & 1 & 1 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
\end{pmatrix}$$

- Column coloring: 5 colors

$$ \begin{pmatrix}
1 & 2 & 3 & 4 & 5 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
\end{pmatrix}$$

- Row coloring: 4 colors

$$ \begin{pmatrix}
1 & 1 & 1 & 1 & 1 \\
2 & 0 & 0 & 0 & 0 \\
3 & 0 & 0 & 0 & 0 \\
4 & 0 & 0 & 0 & 0 \\
\end{pmatrix}$$

- Bicoloring: 2 colors (the top left cell can be split down the diagonal)

$$ \begin{pmatrix}
(1, 2) & 2 & 2 & 2 & 2 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
\end{pmatrix}$$

**Comment by adrhill** [comment]
Closed in #45.
